
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gramatica_gcic_insert;

/** CUP generated class containing symbol constants. */
public class ParserInsertSym {
  /* terminals */
  public static final int MENOR_IGUAL = 17;
  public static final int PROCESS_VAL = 55;
  public static final int ALIGN_VALUE = 61;
  public static final int COLUMN = 68;
  public static final int C_P = 35;
  public static final int TYPE = 42;
  public static final int LLAVE_INI = 10;
  public static final int ROWS = 46;
  public static final int COLOR_HEX = 56;
  public static final int INTEGER_VALUE = 71;
  public static final int CHECKBOX = 65;
  public static final int MAYOR = 5;
  public static final int NAME = 44;
  public static final int ROW = 67;
  public static final int C_GCIC = 20;
  public static final int ALT = 51;
  public static final int TEXT_ALIGN = 41;
  public static final int FONT_VALUE = 60;
  public static final int C_LINK = 23;
  public static final int COMENT_BLOCK = 53;
  public static final int IGUAL_IGUAL = 15;
  public static final int ALL_CHARACTERS = 74;
  public static final int C_OPTION = 29;
  public static final int PAREN_FIN = 9;
  public static final int PERCE_VALUE = 59;
  public static final int BACKGROUND = 37;
  public static final int TEXT = 62;
  public static final int C_SPAM = 25;
  public static final int DOS_PUNTOS = 14;
  public static final int DECIMAL_VALUE = 72;
  public static final int C_BODY = 24;
  public static final int WIDTH = 49;
  public static final int C_TEXTAREA = 27;
  public static final int PUNTO_COMA = 13;
  public static final int PAREN_INI = 8;
  public static final int CLASS = 47;
  public static final int C_DIV = 30;
  public static final int NUMBER = 63;
  public static final int C_HEAD = 21;
  public static final int COMA = 12;
  public static final int C_INPUT = 26;
  public static final int COMENT_LINE = 54;
  public static final int PERCENT = 2;
  public static final int IGUAL = 3;
  public static final int COLS = 45;
  public static final int CORCH_FIN = 7;
  public static final int NO_IGUAL = 16;
  public static final int MENOR = 4;
  public static final int C_BR = 32;
  public static final int DIGIT_VALUE = 66;
  public static final int TEXT_VALUE = 70;
  public static final int EOF = 0;
  public static final int C_TITLE = 22;
  public static final int SIGNO_DIV = 19;
  public static final int C_IMG = 31;
  public static final int CORCH_INI = 6;
  public static final int ID_VALUE = 73;
  public static final int SRC = 48;
  public static final int ID_VALUE_STR = 69;
  public static final int HREF = 36;
  public static final int error = 1;
  public static final int ID = 43;
  public static final int PIXEL_VALUE = 58;
  public static final int COLOR = 38;
  public static final int C_SELECT = 28;
  public static final int COLOR_VALUE = 57;
  public static final int C_H1 = 34;
  public static final int RADIO = 64;
  public static final int HEIGHT = 50;
  public static final int FONT_FAMILY = 40;
  public static final int FONT_SIZE = 39;
  public static final int ONCLICK = 52;
  public static final int C_BUTTON = 33;
  public static final int LLAVE_FIN = 11;
  public static final int MAYOR_IGUAL = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PERCENT",
  "IGUAL",
  "MENOR",
  "MAYOR",
  "CORCH_INI",
  "CORCH_FIN",
  "PAREN_INI",
  "PAREN_FIN",
  "LLAVE_INI",
  "LLAVE_FIN",
  "COMA",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "IGUAL_IGUAL",
  "NO_IGUAL",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "SIGNO_DIV",
  "C_GCIC",
  "C_HEAD",
  "C_TITLE",
  "C_LINK",
  "C_BODY",
  "C_SPAM",
  "C_INPUT",
  "C_TEXTAREA",
  "C_SELECT",
  "C_OPTION",
  "C_DIV",
  "C_IMG",
  "C_BR",
  "C_BUTTON",
  "C_H1",
  "C_P",
  "HREF",
  "BACKGROUND",
  "COLOR",
  "FONT_SIZE",
  "FONT_FAMILY",
  "TEXT_ALIGN",
  "TYPE",
  "ID",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "COMENT_BLOCK",
  "COMENT_LINE",
  "PROCESS_VAL",
  "COLOR_HEX",
  "COLOR_VALUE",
  "PIXEL_VALUE",
  "PERCE_VALUE",
  "FONT_VALUE",
  "ALIGN_VALUE",
  "TEXT",
  "NUMBER",
  "RADIO",
  "CHECKBOX",
  "DIGIT_VALUE",
  "ROW",
  "COLUMN",
  "ID_VALUE_STR",
  "TEXT_VALUE",
  "INTEGER_VALUE",
  "DECIMAL_VALUE",
  "ID_VALUE",
  "ALL_CHARACTERS"
  };
}

