
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gramatica_guardado;

/** CUP generated class containing symbol constants. */
public class ParserGuardadoSym {
  /* terminals */
  public static final int DECIMAL_VALUE = 11;
  public static final int COMA = 5;
  public static final int ULTIMO_REGISTRO = 10;
  public static final int VECES_ABIERTO = 7;
  public static final int FALLOS = 9;
  public static final int ID_VALUE = 13;
  public static final int LLAVE_FIN = 4;
  public static final int EOF = 0;
  public static final int LLAVE_INI = 3;
  public static final int IGUAL = 2;
  public static final int error = 1;
  public static final int TEXT_VALUE = 12;
  public static final int ACIERTOS = 8;
  public static final int NAME = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IGUAL",
  "LLAVE_INI",
  "LLAVE_FIN",
  "COMA",
  "NAME",
  "VECES_ABIERTO",
  "ACIERTOS",
  "FALLOS",
  "ULTIMO_REGISTRO",
  "DECIMAL_VALUE",
  "TEXT_VALUE",
  "ID_VALUE"
  };
}

